### ISSUE TITLE
Extra factor 2 in beam_exptan

### ISSUE THREAD

**Issue by zuoshifan** [radiocosmology/driftscan#64]
According to Eq (35) of 1401.2095v1, line 101 in cylbeam.py

``` python
alpha = np.log(2.0) / (2*np.tan(fwhm / 2.0)**2)
```

should be

``` python
alpha = np.log(2.0) / (2*np.tan(fwhm)**2)
```

**Comment by jrs65** [comment]
Woah, this is an old one. The implementation in the code is correct, Eq 35 in the paper seems to have a typo and is missing the  / 2.
