### ISSUE TITLE
Reorganizing beam SVD computations

### ISSUE THREAD

**Issue by sjforeman** [radiocosmology/driftscan#93]
This issue concerns `_generate_svdfiles()` in `beamtransfer.py`:
https://github.com/radiocosmology/driftscan/blob/4f092741c0aac52f0e42b636bf980e3559cbcd07/drift/core/beamtransfer.py#L828

I have a few issues with this routine that I think can be easily fixed:
1. It can be difficult to diagnose problems that occur for a given m. If the m-specific computations were packaged into a separate routine (`_generate_svdfile_m()`), then that routine could be called on its own during debugging.
2. The SVD file for a given m is created before any computations are performed. If the computations for a given m fail, or some other crash occurs, the files will still be on disk, but will contain junk; furthermore, those files will be detected and the corresponding m's will be skipped the next time the code is run. If the file for a given m is created *after* the computations are successfully completed, this problem will be avoided. Alternatively, there could be a "complete" attribute in the file that is initially written as False and only changed to True after successful completion, and the code could check for this attribute in addition to the existence of a file to decide whether to do the computations for that m.
3. Different m's are distributed to different tasks (via `for mi in mpiutil.mpirange(self.telescope.mmax + 1)`) before it is known which SVD files already exist on disk. Thus, if the code is restarted after a crash, some tasks may sit idle if all of their assigned m's finished successfully before the crash. This could be resolved by doing a first pass through all m's to see which files exist on disk, and then distributing the remaining m's between tasks.

Do these fixes sound reasonable? (Tagging @jrs65 and @cahofer in case they have comments before I implement anything)

**Comment by jrs65** [comment]
All these changes sound good to me.
